# Generated by Django 5.2.5 on 2025-09-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_advertisementview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/profile.png', null=True, upload_to='avatars/'),
        ),
    ]
