# Generated by Django 5.2.5 on 2025-10-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
