# Generated by Django 5.2.5 on 2025-10-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_advertisement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
