# Generated by Django 5.2.5 on 2025-11-22 17:42

import backend.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priorty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=backend.storages.MediaStorage(), upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=backend.storages.MediaStorage(), upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/profile.png', null=True, storage=backend.storages.MediaStorage(), upload_to='avatars/'),
        ),
    ]
