# Generated by Django 5.2.5 on 2025-11-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_category_priorty_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='priorty',
            new_name='priority',
        ),
    ]
