# Generated by Django 5.2.5 on 2025-11-23 17:15

import backend.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/profile.png', null=True, storage=backend.storages.MediaStorage(), upload_to='avatars/'),
        ),
    ]
