# Generated by Django 5.2.5 on 2025-11-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
