# Generated by Django 5.2.5 on 2025-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_advertisement_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafielddefinition',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extrafielddefinition',
            name='field_type',
            field=models.CharField(choices=[('char', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('date', 'Date')], max_length=10),
        ),
        migrations.AlterField(
            model_name='extrafielddefinition',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='extrafielddefinition',
            unique_together={('subcategory', 'key')},
        ),
    ]
