# Generated by Django 5.2.5 on 2025-12-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_extrafielddefinition_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='profile',
        ),
    ]
