# Generated by Django 5.2.5 on 2025-12-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_notification_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.extrafielddefinition')),
            ],
        ),
    ]
