# Generated by Django 5.2.5 on 2025-12-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_extrafieldoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafielddefinition',
            name='field_type',
            field=models.CharField(choices=[('char', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('date', 'Date'), ('select', 'Select')], max_length=10),
        ),
    ]
