# Generated by Django 5.2.5 on 2026-01-16 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_extrafielddefinition_field_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advertisementview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='advertisementview',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisementview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='advertisementview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('ad', 'user'), name='unique_ad_user_view'),
        ),
        migrations.AddConstraint(
            model_name='advertisementview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('ad', 'ip_address'), name='unique_ad_ip_view'),
        ),
        migrations.RemoveField(
            model_name='advertisementview',
            name='created_at',
        ),
    ]
