# Generated by Django 5.2.5 on 2026-01-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_advertisementview_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='is_active',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('moderation', 'На модерации'), ('active', 'Активно'), ('rejected', 'Отклонено'), ('archived', 'Архив')], default='moderation', max_length=20),
        ),
    ]
