# Generated by Django 5.2.5 on 2026-01-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_notification_is_deleted_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
