# Generated by Django 5.2.5 on 2026-02-10 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_notification_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status_changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
