# Generated by Django 5.2.5 on 2026-02-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_notification_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
