# Generated by Django 5.2.5 on 2026-04-11 20:11

import backend.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(storage=backend.storages.MediaStorage(), upload_to='advertising/'),
        ),
    ]
