# Generated by Django 5.2.5 on 2026-05-07 15:49

import backend.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='iframe_code',
            field=models.TextField(blank=True, help_text='Iframe or custom HTML code for ad embedding', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, storage=backend.storages.MediaStorage(), upload_to='advertising/mobile/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=backend.storages.MediaStorage(), upload_to='advertising/desktop/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
