# Generated by Django 5.2.5 on 2026-05-14 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_emailchangecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
