# Generated by Django 5.2.5 on 2026-05-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_advertisementview_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='advertisementview',
            name='unique_ad_user_view',
        ),
        migrations.RemoveConstraint(
            model_name='advertisementview',
            name='unique_ad_ip_view',
        ),
    ]
