# Generated by Django 5.2.5 on 2026-06-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_userprofile_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
