# Generated by Django 5.2.5 on 2026-06-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_advertisement_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchangecode',
            name='new_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailchangecode',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
