# Generated by Django 5.2.5 on 2026-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_emailchangecode_new_email_alter_emailchangecode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='ref_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
