# Generated by Django 5.2.5 on 2026-06-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_emailverification_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementimage',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='ads/original/'),
        ),
    ]
