# Generated by Django 5.2.5 on 2026-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_advertisementimage_image_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='referralconversion',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
