# Generated by Django 5.2.5 on 2026-06-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_referral_name_referralconversion_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
